name: CI – Build & Publish - r3edge-spring-flip

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - uses: actions/checkout@v3

      # 2) Installer JDK 21 + cache Gradle
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # 3) Build & Tests
      - name: Build and Test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build --no-daemon --console=plain

      # 4) Publish sur GitHub Packages **seulement** si c'est un tag
      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publish --no-daemon --console=plain
